name: seer_flutter

description:
publish_to:

version: 1.0.0+2

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # 添加这一行

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"



flutter:

  uses-material-design: true
  assets:
    - assets/databases/1.2.7seer.db
    - assets/images/dihuang.png
    - assets/images/diduo.jpg
    - assets/images/placeholders/
    - assets/images/sprites/  # 确保这一行存在
    - assets/images/properties/
    - assets/images/seal/
    - assets/icons/

  fonts:
    - family: CaoShu
      fonts:
        - asset: assets/fonts/caoshu.ttf

