# ios/Podfile
platform :ios, '17.0'  # 根据你的截图，需要 iOS 17.0+

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Flutter 相关依赖
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
    end
  end
end
