# ios/Podfile
platform :ios, '17.0'

target 'Runner' do
  use_frameworks!
  # 移除 pod 'ActivityKit'，因为它是系统框架
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
