name: Generate iOS IPA

on:
  workflow_dispatch:

jobs:
  build-ipa:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS App Bundle
        run: |
          echo "Building iOS app..."
          flutter build ios --release --no-codesign

      - name: Create IPA File
        run: |
          echo "Creating IPA file..."
          # 创建 IPA 目录结构
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          
          # 压缩成 IPA 文件
          zip -r app.ipa Payload
          
          # 移动到标准目录
          mkdir -p build/ios/ipa
          mv app.ipa build/ios/ipa/Runner.ipa
          
          echo "IPA file created successfully!"
          ls -la build/ios/ipa/

      - name: Upload IPA File
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa-file
          path: build/ios/ipa/Runner.ipa
          retention-days: 30
