name: Build Unsigned IPA for Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-unsigned-ipa:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build Unsigned IPA
        run: |
          flutter build ipa --release --no-codesign --verbose

      - name: List build files
        run: ls -la build/ios/ipa/

      - name: Upload Unsigned IPA
        uses: actions/upload-artifact@v3
        with:
          name: unsigned-ios-ipa
          path: build/ios/ipa/*.ipa
          retention-days: 30