name: Install iOS Dependencies
on: [push]
jobs:
  install-pods:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install CocoaPods
        run: cd ios && pod install
      - name: Upload Pods
        uses: actions/upload-artifact@v3
        with:
          name: ios-pods
          path: ios/