name: Install iOS Dependencies

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ios-dependencies:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.4'
        
    - name: Clean and regenerate iOS files
      run: |
        flutter clean
        rm -rf ios/Pods ios/Podfile.lock
        flutter pub get
        # 强制重新生成 iOS 文件
        flutter create --platforms=ios --org com.example.seer_flutter . || echo "Regeneration completed"
        
    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods
        pod setup
        
    - name: Install iOS pods
      run: |
        cd ios
        pod install --repo-update
