name: Install iOS Dependencies
on: [push]
jobs:
  install-pods:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install CocoaPods
        run: cd ios && pod install
      - name: Commit and Push Pods
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add ios/Pods/ ios/Runner.xcworkspace ios/Podfile.lock
          git diff --staged --quiet || git commit -m "chore: add iOS pods dependencies"
          git push